import { StyleSheet } from 'react-native';
import { spacing, radii, shadows } from './theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0b1329',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    width: '100%',
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  headerSubtitle: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '600',
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing['4xl'],
    alignItems: 'center',
  },
  statusBadgeIcon: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.md,
    elevation: 6,
  },
  statusTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: spacing.xs,
    letterSpacing: 1,
  },
  statusSubtitle: {
    fontSize: 13,
    color: '#cbd5e1',
    textAlign: 'center',
    marginBottom: spacing.xl,
    lineHeight: 18,
    fontWeight: '500',
  },
  card: {
    backgroundColor: '#ffffff',
    width: '100%',
    borderRadius: radii['2xl'],
    padding: spacing.xl,
    ...shadows.lg,
    marginBottom: spacing.xl,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: spacing.md,
    marginBottom: spacing.md,
  },
  iconCircle: {
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0f172a',
  },
  cardSubtitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#16a34a',
  },
  list: {
    marginBottom: spacing.md,
  },
  listItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  itemLabel: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  itemValue: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0f172a',
  },
  instructionBox: {
    backgroundColor: '#f0fdf4',
    padding: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    marginTop: spacing.xs,
  },
  instructionText: {
    color: '#15803d',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
  },
  skeletonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.base,
  },
});

export default styles;
